import type { ComponentType } from "react";
import type { PublicComponentId } from "../../data/canonical";
import type { ProductionComponentProps } from "./types";
import {
  AccessibleStatusLegend,
  ApprovalChain,
  AssignmentRoster,
  AuditTimeline,
  BlockIdentityChip,
  BlockRowSelector,
  CorrectionLineage,
  DecisionEvidencePanel,
  EffectiveTimeControl,
  EscalationClock,
  ExceptionCard,
  ExportEvidencePacket,
  MapScopeViewer,
  MissingInformationCallout,
  NotificationCenter,
  OfflineQueueIndicator,
  OperationalAppShell,
  PartialScopeMeter,
  ReconciliationComparison,
  RecordProvenancePanel,
  RecoveryChecklist,
  RoleScopeSwitcher,
  StalenessBadge,
  SyncConflictResolver,
  TransitionActionBar,
  WorkflowStateRail,
  WorkOrderQueue,
} from "./PublicComponents";

export const publicComponentExports: Record<
  PublicComponentId,
  ComponentType<ProductionComponentProps>
> = {
  "CMP-001": WorkOrderQueue,
  "CMP-002": OperationalAppShell,
  "CMP-003": RoleScopeSwitcher,
  "CMP-004": BlockIdentityChip,
  "CMP-005": RecordProvenancePanel,
  "CMP-006": WorkflowStateRail,
  "CMP-007": TransitionActionBar,
  "CMP-008": DecisionEvidencePanel,
  "CMP-009": MissingInformationCallout,
  "CMP-010": ExceptionCard,
  "CMP-011": RecoveryChecklist,
  "CMP-012": PartialScopeMeter,
  "CMP-013": CorrectionLineage,
  "CMP-014": AuditTimeline,
  "CMP-015": OfflineQueueIndicator,
  "CMP-016": SyncConflictResolver,
  "CMP-017": StalenessBadge,
  "CMP-018": NotificationCenter,
  "CMP-019": EscalationClock,
  "CMP-020": AssignmentRoster,
  "CMP-021": BlockRowSelector,
  "CMP-022": EffectiveTimeControl,
  "CMP-026": MapScopeViewer,
  "CMP-033": ApprovalChain,
  "CMP-034": ReconciliationComparison,
  "CMP-035": ExportEvidencePacket,
  "CMP-036": AccessibleStatusLegend,
};
